export const LINKS = [{
    to: '/',
    title: 'Home',
    class: 'profile',
    order: 1,
  }, {
    to: '/About',
    title: 'About',
    class: 'about',
    order: 2,
  }, {
    to: '/Portfolio',
    title: 'Portfolio',
    class: 'portfolio',
    order: 3,
  }, {
    to: '/Services',
    title: 'Services',
    class: 'services',
    order: 4,
  }, {
    to: '/Skills',
    title: 'Skills',
    class: 'skills',
    order: 5,
  }, {
    to: '/Contact',
    title: 'Contact',
    class: 'contact',
    order: 6,
}];